name: 'Dependency Review'
on: [pull_request, merge_group]

permissions: read-all

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - name: Clone OpenVINO
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Dependency Review
        uses: actions/dependency-review-action@3b139cfc5fae8b618d3eae3675e383bb1769c019 # v4.5.0
        with:
          config-file: './.github/dependency_review.yml'
          base-ref: ${{ github.pull_request.base.sha || github.event.merge_group.base_ref }}
          head-ref: ${{ github.pull_request.head.sha || github.ref }}
